name: nnbdc
description: 泡泡单词 - 智能背单词应用

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# 升级时修改这里
version: 25.10.13+25101301

environment:
  sdk: ^3.4.0

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  flutter_svg: ^2.0.14
  simple_animations: ^5.1.0
  email_validator: ^3.0.0
  toastification: ^2.3.0
  dio: ^5.7.0
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0
  retrofit: ^4.4.2
  retrofit_generator: ^9.1.9
  logger: ^2.5.0 #for logging purpose
  dio_cookie_manager:
  cookie_jar: ^4.0.8
  drift: ^2.21.0
  sqlite3_flutter_libs: ^0.5.26
  path: ^1.8.0
  path_provider: ^2.1.4
  path_provider_platform_interface: ^2.1.2
  get: ^4.6.1
  provider: ^6.0.1
  package_info_plus: ^8.0.3
  flutter_downloader: ^1.7.1
  permission_handler: ^11.3.1
  animated_text_kit: ^4.2.1
  day_night_switcher: ^0.2.0+1
  percent_indicator: ^4.0.0
  confirm_dialog: ^1.0.0
  flutter_reorderable_list: ^1.1.0
  open_file: ^3.2.1
  audioplayers: ^6.4.0
  flutter_cache_manager: ^3.1.3
  flutter_animation_progress_bar: ^2.0.1
  scrollable_positioned_list: ^0.3.8
  lpinyin: ^2.0.3
  socket_io_client: ^1.0.2
  flame: ^1.2.1
  flame_audio: ^2.10.4
  video_player: ^2.9.2
  flutter_keyboard_visibility: ^6.0.0
  cached_network_image: ^3.4.1
  image_network: ^2.5.6
  flutter_inappwebview: ^6.1.5
  url_launcher: ^6.3.1
  appcheck: ^1.5.2
  get_storage: ^2.1.1
  chat_bubbles: ^1.3.0
  intl: ^0.19.0
  drift_db_viewer: ^2.1.0
  equatable: ^2.0.7
  flutter_native_splash: ^2.4.3 
  fluwx: ^4.1.0  # 微信登录SDK
  connectivity_plus: ^6.0.5  # 网络连接检测

  http: any
  uuid: any
  app_settings: ^6.1.1
dev_dependencies:
  analyzer: ^7.7.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.21.2
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.14.4
  icons_launcher: ^3.0.0


dependency_overrides:
  logging: 1.3.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add images to your application, add an images section, like this:
  assets:
    - assets/images/
    - assets/privacy.html
    - assets/protocol.html
    - assets/audio/
    - assets/video/
    - assets/fonts/
    - assets/cmudict.dict
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding images from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: NotoSansSC
      fonts:
        - asset: assets/fonts/NotoSansSC-Regular.ttf
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

# 插件说明： https://pub.dev/packages/flutter_native_splash
# dart run flutter_native_splash:create
# 原生闪屏页配置：只使用纯logo图片，不包含文字，便于维护
flutter_native_splash:
  color: "#42a5f5"
  image: "assets/images/logo.png"
  android: true
  ios: true
  web: false

# 应用图标生成配置（使用 SVG 源图）
flutter_launcher_icons:
  android: true
  ios: true
  macos:
    generate: true
    image_path: assets/images/logo.png
  windows:
    generate: true
    image_path: assets/images/logo.png
    icon_size: 256
  # 注意：生成器不接受 SVG，需先导出 PNG
  image_path: assets/images/logo.png
  min_sdk_android: 21
  remove_alpha_ios: true

# 如改用 icons_launcher，可保留此段。但当前生成图标将使用 flutter_launcher_icons 与 PNG。
icons_launcher:
  image_path: assets/images/logo.png
  platforms:
    android:
      enable: false
    ios:
      enable: false
    windows:
      enable: false
